(global-set-key (kbd "C-x w") 'clean-and-save-buffer)
(global-set-key (kbd "C-x b") 'ibuffer)
(global-set-key (kbd "C-x f") 'fiplr-find-file)
(global-set-key (kbd "C-x g") 'magit-status)
(global-set-key (kbd "C-x a") 'ack-and-a-half)
(global-set-key (kbd "C-x s") 'ag-project)
(global-set-key (kbd "C-x n") (kbd "C-c s"))
(global-set-key (kbd "C-x l") 'goto-line)
(global-set-key (kbd "C-x d") 'dash-at-point)
(global-set-key (kbd "C-u")   'undo)
(global-set-key (kbd "C-S-u") 'redo)
(global-set-key (kbd "C-x i") 'change-inner)
(global-set-key (kbd "C-x o") 'change-outer)

(provide 'key-bindings)
