export HOMEBREW_HOME=/opt/homebrew
export PATH=${HOMEBREW_HOME}/bin:${PATH}
export PATH=/Users/jperkelens/.local/bin:${PATH}

# JVMs
export PATH=${HOMEBREW_HOME}/opt/scala@2.12/bin:$PATH
export PATH=${HOMEBREW_HOME}/opt/openjdk@11/bin:$PATH

export JAVA_HOME=${HOMEBREW_HOME}/opt/openjdk@11/bin

# Pyenv
# $(pyenv init -) breaks zsh -- these do the job

export PATH=/Users/jperkelens/.pyenv/shims:${PATH} 
export PYENV_SHELL=zsh 

# SBT GITLAB
export CI_JOB_TOKEN="glpat-x6N_jCyeLZT9Duxo2RMG"

# AWS 
export AWS_PROFILE=dev-shared
export AWS_SDK_LOAD_CONFIG=1

# Delta / Hive
export HIVE_SITE_DIR=~/.config/hive
export HIVE_AUX_JARS_PATH=~/.config/hive

if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

