#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# set up prompt
autoload -Uz promptinit
promptinit
prompt matt

alias emacs="/usr/local/Cellar/emacs/25.3/bin/emacs"

# Customize to your needs...
export BUNYAN_NO_PAGER=true
export EDITOR=vim
export NODE_ENV=development
export BOOT_JVM_OPTIONS="-client -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Xmx256m -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -Xverify:none"

if [[ "$OSTYPE" == "linux-gnu" ]]; then
  # linux config
elif [[ "$OSTYPE" == "darwin"* ]]; then
  # Mac OSX config
  alias vim='nvim'
fi

LUNCHY_DIR=$(dirname `gem which lunchy`)/../extras
  if [ -f $LUNCHY_DIR/lunchy-completion.zsh ]; then
    . $LUNCHY_DIR/lunchy-completion.zsh
fi

if [[ -s "/usr/local/share/zsh/site-functions/_aws" ]]; then
  source "/usr/local/share/zsh/site-functions/_aws"
fi

